# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: affef478d7d4e6fe4171e73cdf55fb9f22bb92db735ab2a9cde424704235788ccd19e732924b97f47b3416482d031ad3b150d6016bfc281d0fca99ef4ba78237

test:
  secret_key_base: cf3ae34c96ece10c2fe581a1fbd72977491812519458e40186ee46e2c19dd21bed99da027146b8428baa167de6141b3446cc7b7a1006c0e88db927d3bbe87930

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
